// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotogpApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotogpApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotogpApi.Models.GrandPrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Circuit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCourse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstTermine")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GrandsPrix");
                });

            modelBuilder.Entity("MotogpApi.Models.Pari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePari")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstValide")
                        .HasColumnType("boolean");

                    b.Property<int>("GrandPrixId")
                        .HasColumnType("integer");

                    b.Property<int>("PiloteP1Id")
                        .HasColumnType("integer");

                    b.Property<int>("PiloteP2Id")
                        .HasColumnType("integer");

                    b.Property<int>("PiloteP3Id")
                        .HasColumnType("integer");

                    b.Property<int>("PointsGagnes")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrandPrixId");

                    b.HasIndex("PiloteP1Id");

                    b.HasIndex("PiloteP2Id");

                    b.HasIndex("PiloteP3Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Paris");
                });

            modelBuilder.Entity("MotogpApi.Models.Pilote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Equipe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pilotes");
                });

            modelBuilder.Entity("MotogpApi.Models.Resultat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GrandPrixId")
                        .HasColumnType("integer");

                    b.Property<int>("PiloteId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrandPrixId");

                    b.HasIndex("PiloteId");

                    b.ToTable("Resultats");
                });

            modelBuilder.Entity("MotogpApi.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EstAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MotogpApi.Models.Pari", b =>
                {
                    b.HasOne("MotogpApi.Models.GrandPrix", "GrandPrix")
                        .WithMany("Paris")
                        .HasForeignKey("GrandPrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotogpApi.Models.Pilote", "PiloteP1")
                        .WithMany()
                        .HasForeignKey("PiloteP1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotogpApi.Models.Pilote", "PiloteP2")
                        .WithMany()
                        .HasForeignKey("PiloteP2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotogpApi.Models.Pilote", "PiloteP3")
                        .WithMany()
                        .HasForeignKey("PiloteP3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotogpApi.Models.Utilisateur", "Utilisateur")
                        .WithMany("Paris")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrandPrix");

                    b.Navigation("PiloteP1");

                    b.Navigation("PiloteP2");

                    b.Navigation("PiloteP3");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("MotogpApi.Models.Resultat", b =>
                {
                    b.HasOne("MotogpApi.Models.GrandPrix", "GrandPrix")
                        .WithMany("Resultats")
                        .HasForeignKey("GrandPrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotogpApi.Models.Pilote", "Pilote")
                        .WithMany("Resultats")
                        .HasForeignKey("PiloteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrandPrix");

                    b.Navigation("Pilote");
                });

            modelBuilder.Entity("MotogpApi.Models.GrandPrix", b =>
                {
                    b.Navigation("Paris");

                    b.Navigation("Resultats");
                });

            modelBuilder.Entity("MotogpApi.Models.Pilote", b =>
                {
                    b.Navigation("Resultats");
                });

            modelBuilder.Entity("MotogpApi.Models.Utilisateur", b =>
                {
                    b.Navigation("Paris");
                });
#pragma warning restore 612, 618
        }
    }
}
